[package]
name = "kajota-tools"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
regex = "1.11"

[[bin]]
name = "check_true_flac"
path = "src/bin/check_true_flac.rs"

[[bin]]
name = "compress-video"
path = "src/bin/compress_video.rs"

[[bin]]
name = "is-avif"
path = "src/bin/is_avif.rs"

[[bin]]
name = "pformat"
path = "src/bin/pformat.rs"
